name: Test/Lint/Fmt/Vet
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    env:
      CHIA_SSL_DIR: "/root/.chia/mainnet/config/ssl"
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: make test-coverage
