name: Test/Lint/Fmt/Vet
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    steps:
      - uses: actions/checkout@v3

      - name: Get config
        run: |
          apt-get update
          apt-get install ca-certificates curl gnupg -y
          curl -sL https://repo.chia.net/FD39E6D3.pubkey.asc | gpg --dearmor -o /usr/share/keyrings/chia.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/debian/ stable main" | tee /etc/apt/sources.list.d/chia.list > /dev/null
          apt-get update
          apt-get install chia-blockchain-cli
          chia init

      - name: Test
        run: make test-coverage
