name: Test/Lint/Fmt/Vet
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    steps:
      - uses: actions/checkout@v3

      - name: Get config
        run: |
          wget https://raw.githubusercontent.com/Chia-Network/chia-blockchain/main/chia/util/initial-config.yaml
          mkdir -p ~/.chia/mainnet/config/
          mv initial-config.yaml ~/.chia/mainnet/config/config.yaml

      - name: Test
        run: make test-coverage
